export type Product = { slug:string; name:string; category:string; price:string; priceCents:number; note:string; sizes:string[]; colorways:string[]; images:{src:string;alt:string}[]; status:string };

export const products: Product[] = [
  { slug:"money-calling-tee", name:"MONEY CALLING TEE", category:"Tee", price:"$55", priceCents:5500, note:"A white graphic tee with an oversized illustrated front print.", sizes:["S","M","L","XL"], colorways:["White"], images:[{src:"/products/money-calling-lifestyle.webp",alt:"Model wearing the white Money Calling graphic tee"},{src:"/products/IMG_6454(2).jpeg",alt:"White Money Calling graphic tee laid flat"}], status:"Current collection" },
  { slug:"desire-pays-long-sleeve", name:"DESIRE PAYS LONG SLEEVE", category:"Long Sleeve", price:"$75", priceCents:7500, note:"The same full-front collage graphic offered in bone and black.", sizes:["S","M","L","XL"], colorways:["Bone","Black"], images:[{src:"/products/desire-pays-black-lifestyle.webp",alt:"Model wearing the black Desire Pays graphic long-sleeve shirt"},{src:"/products/IMG_6453(2).jpeg",alt:"Bone Desire Pays graphic long-sleeve shirt laid flat"},{src:"/products/IMG_6452(2).jpeg",alt:"Black Desire Pays graphic long-sleeve shirt laid flat"}], status:"Current collection" },
  { slug:"fatal-attraction-tee", name:"FATAL ATTRACTION TEE", category:"Tee", price:"$55", priceCents:5500, note:"A white tee with a warm-toned, vintage-inspired front graphic.", sizes:["S","M","L","XL"], colorways:["White"], images:[{src:"/products/fatal-attraction-lifestyle.webp",alt:"Model wearing the white Fatal Attraction graphic tee"},{src:"/products/IMG_6451(2).jpeg",alt:"White Fatal Attraction graphic tee laid flat"}], status:"Current collection" },
];

export function getProduct(slug:string){ return products.find((product)=>product.slug===slug); }
